### ISSUE TITLE
Xcode icon not rendered

### ISSUE THREAD

**Issue by ubuntudroid** [kvndrsslr/sketchybar-app-font#4]
As reported here there seems to be an issue with the Xcode icon:

https://github.com/FelixKratz/dotfiles/issues/11

The icon doesn't seem to render properly. Mappings are looking good, so that shouldn't be the cause.

**Comment by kvndrsslr** [comment]
I've taken these icons from the simple-bar project and the XCode one seems to not be suited for font rendering below 144pt.
Here is a screenshot from a quick test I did in TextEdit:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/46481738/211357482-c4d19aba-a177-483b-87b9-42d974d8c485.png">

There should be two symbols, one in 144pt and one in 94pt. Only the 144pt renders, due to the lines being way too thin.
It would probably be a good idea to make an alternative icon with less detail and bigger filled-in areas. PRs are welcome and there is a guide on how to make these icons in this projects README! Cheers :)
