### ISSUE TITLE
I cant get ligatures working

### ISSUE THREAD

**Issue by nilsi** [kvndrsslr/sketchybar-app-font#56]
I installed the latest icons:

`curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v2.0.5/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf`

I use kitty as a terminal. 

Now to the problem: I can't add any new icons from the font book. I tried writing for example `:slack:` but it does not render the icon or show up in the bar. I also tried copying from the font book without a result. 

I don't understand why this is not working since the icons are in the font book and the terminal supports ligatures. Any ideas would be appreciated.

**Comment by kvndrsslr** [comment]
The font has been tested in the context of sketchybar. While it should indeed work anywhere with ligature support it arguably abuses the concept of ligatures. A quick search in kitty surfaced this issue which explains it:
https://github.com/kovidgoyal/kitty/issues/7142

So without looking into the code, one of the following happens:

1. kitty renders the symbol but only at `(100/ligature.length)%` - barely visible
2. due to the implications of kittys behavior the developer implemented a max viable ligature length and any ligatures over that length just won't be considered for rendering
